[general]
live_config_reload = true
import = [
  "~/.config/alacritty/theme.toml"
]

[window]

opacity = 0.9
# padding.x = 15
# padding.y = 15

decorations = "None"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 12.0
